
site_name: SQLiteStudio Survival Guide

nav:
  - Archive:
      - Manual (PDF): archive/manual-2.1.md
  - Examples:
      - Foreign Key Rebuild: examples/foreign_key_rebuild_example.md
      - Index Loss Example: examples/index_loss_example.md
      - NOT NULL Example: examples/rebuild_not_null_example.md
  - Tests:
      - FK Addition Rebuild: tests/test_fk_addition_rebuild.md
      - Index Survival on Rename: tests/test_index_survival_on_rename.md
      - NOT NULL Commit Effect: tests/test_not_null_commit_effect.md
      - Table Copy Rollback: tests/test_table_copy_rollback_case.md
  - Tools:
      - Foreign Key Safety: tools/foreign_key_safety.md
      - Index Checker: tools/index_checker.md
      - Index Repair: tools/index_repair.md
      - Sqlite Commit Watch: tools/sqlite_commit_watch.md
      - Structure Diff: tools/structure_diff.md

theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: light blue

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
